name: Event Workflow # optional

on: # GE workflow will be triggered
  push:
    branches:
      - "master"
  
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Custom 1
        run: |
          sudo apt update
          sudo apt list --installed
      - name: Trying with the ubuntu runner
        run: |
          pwd
          mkdir random
          cd random
          touch random.txt
          pwd