name: Event Workflow # optional

on: # GE workflow will be triggered
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      message:
        description: Give a message
        required: true
        default: Random message
  
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Custom 1
        run: |
          sudo apt update
          sudo apt list --installed
      - name: Trying with the ubuntu runner
        run: |
          pwd
          mkdir random
          cd random
          touch random.txt
          pwd
  
  job2:
    name: Second job
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: write-output "Hello world"
        shell: pwsh

  job3:
    name: Third job
    runs-on: ubuntu-latest
    steps:
      - name : Printing what the workflow_dispatch event is having
        run: echo "${{github.event.inputs.message}}"

  job6:
    name: Python dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Installing Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Printing the python env    
        run: pip list
      
      - name: Installing Flake8
        run: pip install flake8
      
      - name: Python env
        run: pip list

      - name: Lint check
        run: flake8 



