name: Event Workflow # optional

on: # GE workflow will be triggered
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      message:
        description: Give a message
        required: true
        default: Random message
  
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Custom 1
        run: |
          sudo apt update
          sudo apt list --installed
      - name: Trying with the ubuntu runner
        run: |
          pwd
          mkdir random
          cd random
          touch random.txt
          pwd
  
  job2:
    name: Second job
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: write-output "Hello world"
        shell: pwsh

  job3:
    name: Third job
    runs-on: ubuntu-latest
    steps:
      - name : Printing what the workflow_dispatch event is having
        run: echo "${{github.event.inputs.message}}"



